language: cpp
compiler: clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq mpich2 libmpich2-3 libmpich2-dev gcc-4.9 gcc-5 clang-3.5
script: sh ./test.sh